require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Admin::RolesController do
  
  before(:each) do
    sign_in FactoryGirl.create(:user)
  end
  
  # This should return the minimal set of attributes required to create a valid
  # Admin::Role. As you add validations to Admin::Role, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Admin::RolesController. Be sure to keep this updated too.
  let(:valid_session) { {"warden.user.user.key" => session["warden.user.user.key"]} }

  describe "GET index" do
    it "assigns all admin_roles as @admin_roles" do
      role = Admin::Role.create! valid_attributes
      get :index, {}, valid_session
      assigns(:admin_roles).should eq([role])
    end
  end

  describe "GET show" do
    it "assigns the requested admin_role as @admin_role" do
      role = Admin::Role.create! valid_attributes
      get :show, {:id => role.to_param}, valid_session
      assigns(:admin_role).should eq(role)
    end
  end

  describe "GET new" do
    it "assigns a new admin_role as @admin_role" do
      get :new, {}, valid_session
      assigns(:admin_role).should be_a_new(Admin::Role)
    end
  end

  describe "GET edit" do
    it "assigns the requested admin_role as @admin_role" do
      role = Admin::Role.create! valid_attributes
      get :edit, {:id => role.to_param}, valid_session
      assigns(:admin_role).should eq(role)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Admin::Role" do
        expect {
          post :create, {:admin_role => valid_attributes}, valid_session
        }.to change(Admin::Role, :count).by(1)
      end

      it "assigns a newly created admin_role as @admin_role" do
        post :create, {:admin_role => valid_attributes}, valid_session
        assigns(:admin_role).should be_a(Admin::Role)
        assigns(:admin_role).should be_persisted
      end

      it "redirects to the created admin_role" do
        post :create, {:admin_role => valid_attributes}, valid_session
        response.should redirect_to(Admin::Role.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved admin_role as @admin_role" do
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Role.any_instance.stub(:save).and_return(false)
        post :create, {:admin_role => { "name" => "invalid value" }}, valid_session
        assigns(:admin_role).should be_a_new(Admin::Role)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Role.any_instance.stub(:save).and_return(false)
        post :create, {:admin_role => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested admin_role" do
        role = Admin::Role.create! valid_attributes
        # Assuming there are no other admin_roles in the database, this
        # specifies that the Admin::Role created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Admin::Role.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => role.to_param, :admin_role => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested admin_role as @admin_role" do
        role = Admin::Role.create! valid_attributes
        put :update, {:id => role.to_param, :admin_role => valid_attributes}, valid_session
        assigns(:admin_role).should eq(role)
      end

      it "redirects to the admin_role" do
        role = Admin::Role.create! valid_attributes
        put :update, {:id => role.to_param, :admin_role => valid_attributes}, valid_session
        response.should redirect_to(role)
      end
    end

    describe "with invalid params" do
      it "assigns the admin_role as @admin_role" do
        role = Admin::Role.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Role.any_instance.stub(:save).and_return(false)
        put :update, {:id => role.to_param, :admin_role => { "name" => "invalid value" }}, valid_session
        assigns(:admin_role).should eq(role)
      end

      it "re-renders the 'edit' template" do
        role = Admin::Role.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Role.any_instance.stub(:save).and_return(false)
        put :update, {:id => role.to_param, :admin_role => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested admin_role" do
      role = Admin::Role.create! valid_attributes
      expect {
        delete :destroy, {:id => role.to_param}, valid_session
      }.to change(Admin::Role, :count).by(-1)
    end

    it "redirects to the admin_roles list" do
      role = Admin::Role.create! valid_attributes
      delete :destroy, {:id => role.to_param}, valid_session
      response.should redirect_to(admin_roles_url)
    end
  end

end
