require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Scouting::ControlTowersController do

  before(:each) do
    @role = FactoryGirl.create(:admin_role)
    @user = FactoryGirl.create(:user)
    @user.roles << @role
    sign_in @user
    
    @control_tower = FactoryGirl.create(:scouting_control_tower)
  end

  # This should return the minimal set of attributes required to create a valid
  # Scouting::ControlTower. As you add validations to Scouting::ControlTower, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { 
    { "region_id" => 1, "constellation_id" => 1, "solar_system_id" => 1, "moon_id" => 1, "control_tower_type_id" => 1 } 
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Scouting::ControlTowersController. Be sure to keep this updated too.
  let(:valid_session) { {"warden.user.user.key" => session["warden.user.user.key"]} }

  describe "GET index" do
    it "assigns all scouting_control_towers as @scouting_control_towers" do
      get :index, {}, valid_session
      assigns(:scouting_control_towers).should eq([@control_tower])
    end
  end

  describe "GET show" do
    it "assigns the requested scouting_control_tower as @scouting_control_tower" do
      get :show, {:id => @control_tower.to_param}, valid_session
      assigns(:scouting_control_tower).should eq(@control_tower)
    end
  end

  describe "GET new" do
    it "assigns a new scouting_control_tower as @scouting_control_tower" do
      get :new, {}, valid_session
      assigns(:scouting_control_tower).should be_a_new(Scouting::ControlTower)
    end
  end

  describe "GET edit" do
    it "assigns the requested scouting_control_tower as @scouting_control_tower" do
      get :edit, {:id => @control_tower.to_param}, valid_session
      assigns(:scouting_control_tower).should eq(@control_tower)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Scouting::ControlTower" do
        expect {
          post :create, {:scouting_control_tower => valid_attributes}, valid_session
        }.to change(Scouting::ControlTower, :count).by(1)
      end

      it "assigns a newly created scouting_control_tower as @scouting_control_tower" do
        post :create, {:scouting_control_tower => valid_attributes}, valid_session
        assigns(:scouting_control_tower).should be_a(Scouting::ControlTower)
        assigns(:scouting_control_tower).should be_persisted
      end

      it "redirects to the created scouting_control_tower" do
        post :create, {:scouting_control_tower => valid_attributes}, valid_session
        response.should redirect_to(Scouting::ControlTower.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved scouting_control_tower as @scouting_control_tower" do
        # Trigger the behavior that occurs when invalid params are submitted
        Scouting::ControlTower.any_instance.stub(:save).and_return(false)
        post :create, {:scouting_control_tower => { "region_id" => "invalid value" }}, valid_session
        assigns(:scouting_control_tower).should be_a_new(Scouting::ControlTower)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Scouting::ControlTower.any_instance.stub(:save).and_return(false)
        post :create, {:scouting_control_tower => { "region_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested scouting_control_tower" do
        control_tower = Scouting::ControlTower.create! valid_attributes
        # Assuming there are no other scouting_control_towers in the database, this
        # specifies that the Scouting::ControlTower created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Scouting::ControlTower.any_instance.should_receive(:update_attributes).with({ "region_id" => "1" })
        put :update, {:id => control_tower.to_param, :scouting_control_tower => { "region_id" => "1" }}, valid_session
      end

      it "assigns the requested scouting_control_tower as @scouting_control_tower" do
        control_tower = Scouting::ControlTower.create! valid_attributes
        put :update, {:id => control_tower.to_param, :scouting_control_tower => valid_attributes}, valid_session
        assigns(:scouting_control_tower).should eq(control_tower)
      end

      it "redirects to the scouting_control_tower" do
        control_tower = Scouting::ControlTower.create! valid_attributes
        put :update, {:id => control_tower.to_param, :scouting_control_tower => valid_attributes}, valid_session
        response.should redirect_to(control_tower)
      end
    end

    describe "with invalid params" do
      it "assigns the scouting_control_tower as @scouting_control_tower" do
        control_tower = Scouting::ControlTower.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Scouting::ControlTower.any_instance.stub(:save).and_return(false)
        put :update, {:id => control_tower.to_param, :scouting_control_tower => { "region_id" => "invalid value" }}, valid_session
        assigns(:scouting_control_tower).should eq(control_tower)
      end

      it "re-renders the 'edit' template" do
        control_tower = Scouting::ControlTower.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Scouting::ControlTower.any_instance.stub(:save).and_return(false)
        put :update, {:id => control_tower.to_param, :scouting_control_tower => { "region_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested scouting_control_tower" do
      control_tower = Scouting::ControlTower.create! valid_attributes
      expect {
        delete :destroy, {:id => control_tower.to_param}, valid_session
      }.to change(Scouting::ControlTower, :count).by(-1)
    end

    it "redirects to the scouting_control_towers list" do
      control_tower = Scouting::ControlTower.create! valid_attributes
      delete :destroy, {:id => control_tower.to_param}, valid_session
      response.should redirect_to(scouting_control_towers_url)
    end
  end

end
