require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Scouting::ReportsController do

  # This should return the minimal set of attributes required to create a valid
  # Scouting::Report. As you add validations to Scouting::Report, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "star_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Scouting::ReportsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all scouting_reports as @scouting_reports" do
      report = Scouting::Report.create! valid_attributes
      get :index, {}, valid_session
      assigns(:scouting_reports).should eq([report])
    end
  end

  describe "GET show" do
    it "assigns the requested scouting_report as @scouting_report" do
      report = Scouting::Report.create! valid_attributes
      get :show, {:id => report.to_param}, valid_session
      assigns(:scouting_report).should eq(report)
    end
  end

  describe "GET new" do
    it "assigns a new scouting_report as @scouting_report" do
      get :new, {}, valid_session
      assigns(:scouting_report).should be_a_new(Scouting::Report)
    end
  end

  describe "GET edit" do
    it "assigns the requested scouting_report as @scouting_report" do
      report = Scouting::Report.create! valid_attributes
      get :edit, {:id => report.to_param}, valid_session
      assigns(:scouting_report).should eq(report)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Scouting::Report" do
        expect {
          post :create, {:scouting_report => valid_attributes}, valid_session
        }.to change(Scouting::Report, :count).by(1)
      end

      it "assigns a newly created scouting_report as @scouting_report" do
        post :create, {:scouting_report => valid_attributes}, valid_session
        assigns(:scouting_report).should be_a(Scouting::Report)
        assigns(:scouting_report).should be_persisted
      end

      it "redirects to the created scouting_report" do
        post :create, {:scouting_report => valid_attributes}, valid_session
        response.should redirect_to(Scouting::Report.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved scouting_report as @scouting_report" do
        # Trigger the behavior that occurs when invalid params are submitted
        Scouting::Report.any_instance.stub(:save).and_return(false)
        post :create, {:scouting_report => { "star_id" => "invalid value" }}, valid_session
        assigns(:scouting_report).should be_a_new(Scouting::Report)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Scouting::Report.any_instance.stub(:save).and_return(false)
        post :create, {:scouting_report => { "star_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested scouting_report" do
        report = Scouting::Report.create! valid_attributes
        # Assuming there are no other scouting_reports in the database, this
        # specifies that the Scouting::Report created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Scouting::Report.any_instance.should_receive(:update_attributes).with({ "star_id" => "1" })
        put :update, {:id => report.to_param, :scouting_report => { "star_id" => "1" }}, valid_session
      end

      it "assigns the requested scouting_report as @scouting_report" do
        report = Scouting::Report.create! valid_attributes
        put :update, {:id => report.to_param, :scouting_report => valid_attributes}, valid_session
        assigns(:scouting_report).should eq(report)
      end

      it "redirects to the scouting_report" do
        report = Scouting::Report.create! valid_attributes
        put :update, {:id => report.to_param, :scouting_report => valid_attributes}, valid_session
        response.should redirect_to(report)
      end
    end

    describe "with invalid params" do
      it "assigns the scouting_report as @scouting_report" do
        report = Scouting::Report.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Scouting::Report.any_instance.stub(:save).and_return(false)
        put :update, {:id => report.to_param, :scouting_report => { "star_id" => "invalid value" }}, valid_session
        assigns(:scouting_report).should eq(report)
      end

      it "re-renders the 'edit' template" do
        report = Scouting::Report.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Scouting::Report.any_instance.stub(:save).and_return(false)
        put :update, {:id => report.to_param, :scouting_report => { "star_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested scouting_report" do
      report = Scouting::Report.create! valid_attributes
      expect {
        delete :destroy, {:id => report.to_param}, valid_session
      }.to change(Scouting::Report, :count).by(-1)
    end

    it "redirects to the scouting_reports list" do
      report = Scouting::Report.create! valid_attributes
      delete :destroy, {:id => report.to_param}, valid_session
      response.should redirect_to(scouting_reports_url)
    end
  end

end
